/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as GuestOrderRouteImport } from './routes/guest-order'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PointsRouteImport } from './routes/points'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AccountInquiriesRouteImport } from './routes/account_.inquiries'
import { Route as AccountWishlistRouteImport } from './routes/account_.wishlist'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as CheckoutCompleteRouteImport } from './routes/checkout.complete'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as AccountReviewsIndexRouteImport } from './routes/account_.reviews.index'
import { Route as AccountSupportIndexRouteImport } from './routes/account_.support.index'
import { Route as AccountSupportInquiryIdRouteImport } from './routes/account_.support.$inquiryId'
import { Route as AccountSupportNewRouteImport } from './routes/account_.support.new'
import { Route as AccountReviewsEditReviewIdRouteImport } from './routes/account_.reviews.edit.$reviewId'
import { Route as AccountReviewsWriteOrderItemIdRouteImport } from './routes/account_.reviews.write.$orderItemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestOrderRoute = GuestOrderRouteImport.update({
  id: '/guest-order',
  path: '/guest-order',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountInquiriesRoute = AccountInquiriesRouteImport.update({
  id: '/account_/inquiries',
  path: '/account/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/account_/wishlist',
  path: '/account/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCompleteRoute = CheckoutCompleteRouteImport.update({
  id: '/checkout/complete',
  path: '/checkout/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountReviewsIndexRoute = AccountReviewsIndexRouteImport.update({
  id: '/account_/reviews/',
  path: '/account/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSupportIndexRoute = AccountSupportIndexRouteImport.update({
  id: '/account_/support/',
  path: '/account/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSupportInquiryIdRoute = AccountSupportInquiryIdRouteImport.update({
  id: '/account_/support/$inquiryId',
  path: '/account/support/$inquiryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSupportNewRoute = AccountSupportNewRouteImport.update({
  id: '/account_/support/new',
  path: '/account/support/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountReviewsEditReviewIdRoute =
  AccountReviewsEditReviewIdRouteImport.update({
    id: '/account_/reviews/edit/$reviewId',
    path: '/account/reviews/edit/$reviewId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountReviewsWriteOrderItemIdRoute =
  AccountReviewsWriteOrderItemIdRouteImport.update({
    id: '/account_/reviews/write/$orderItemId',
    path: '/account/reviews/write/$orderItemId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/coupons': typeof CouponsRoute
  '/guest-order': typeof GuestOrderRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/points': typeof PointsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/inquiries': typeof AccountInquiriesRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/account/support/$inquiryId': typeof AccountSupportInquiryIdRoute
  '/account/support/new': typeof AccountSupportNewRoute
  '/account/reviews/': typeof AccountReviewsIndexRoute
  '/account/support/': typeof AccountSupportIndexRoute
  '/account/reviews/edit/$reviewId': typeof AccountReviewsEditReviewIdRoute
  '/account/reviews/write/$orderItemId': typeof AccountReviewsWriteOrderItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/coupons': typeof CouponsRoute
  '/guest-order': typeof GuestOrderRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/points': typeof PointsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/inquiries': typeof AccountInquiriesRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/checkout': typeof CheckoutIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/account/support/$inquiryId': typeof AccountSupportInquiryIdRoute
  '/account/support/new': typeof AccountSupportNewRoute
  '/account/reviews': typeof AccountReviewsIndexRoute
  '/account/support': typeof AccountSupportIndexRoute
  '/account/reviews/edit/$reviewId': typeof AccountReviewsEditReviewIdRoute
  '/account/reviews/write/$orderItemId': typeof AccountReviewsWriteOrderItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/coupons': typeof CouponsRoute
  '/guest-order': typeof GuestOrderRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/points': typeof PointsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account_/inquiries': typeof AccountInquiriesRoute
  '/account_/wishlist': typeof AccountWishlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/account_/support/$inquiryId': typeof AccountSupportInquiryIdRoute
  '/account_/support/new': typeof AccountSupportNewRoute
  '/account_/reviews/': typeof AccountReviewsIndexRoute
  '/account_/support/': typeof AccountSupportIndexRoute
  '/account_/reviews/edit/$reviewId': typeof AccountReviewsEditReviewIdRoute
  '/account_/reviews/write/$orderItemId': typeof AccountReviewsWriteOrderItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/coupons'
    | '/guest-order'
    | '/help'
    | '/login'
    | '/points'
    | '/privacy'
    | '/search'
    | '/signup'
    | '/terms'
    | '/account/inquiries'
    | '/account/wishlist'
    | '/auth/callback'
    | '/checkout/complete'
    | '/checkout/return'
    | '/collections/$slug'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/checkout/'
    | '/collections/'
    | '/orders/'
    | '/products/'
    | '/account/support/$inquiryId'
    | '/account/support/new'
    | '/account/reviews/'
    | '/account/support/'
    | '/account/reviews/edit/$reviewId'
    | '/account/reviews/write/$orderItemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/coupons'
    | '/guest-order'
    | '/help'
    | '/login'
    | '/points'
    | '/privacy'
    | '/search'
    | '/signup'
    | '/terms'
    | '/account/inquiries'
    | '/account/wishlist'
    | '/auth/callback'
    | '/checkout/complete'
    | '/checkout/return'
    | '/collections/$slug'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/checkout'
    | '/collections'
    | '/orders'
    | '/products'
    | '/account/support/$inquiryId'
    | '/account/support/new'
    | '/account/reviews'
    | '/account/support'
    | '/account/reviews/edit/$reviewId'
    | '/account/reviews/write/$orderItemId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/coupons'
    | '/guest-order'
    | '/help'
    | '/login'
    | '/points'
    | '/privacy'
    | '/search'
    | '/signup'
    | '/terms'
    | '/account_/inquiries'
    | '/account_/wishlist'
    | '/auth/callback'
    | '/checkout/complete'
    | '/checkout/return'
    | '/collections/$slug'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/checkout/'
    | '/collections/'
    | '/orders/'
    | '/products/'
    | '/account_/support/$inquiryId'
    | '/account_/support/new'
    | '/account_/reviews/'
    | '/account_/support/'
    | '/account_/reviews/edit/$reviewId'
    | '/account_/reviews/write/$orderItemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CouponsRoute: typeof CouponsRoute
  GuestOrderRoute: typeof GuestOrderRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  PointsRoute: typeof PointsRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AccountInquiriesRoute: typeof AccountInquiriesRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CheckoutCompleteRoute: typeof CheckoutCompleteRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  AccountSupportInquiryIdRoute: typeof AccountSupportInquiryIdRoute
  AccountSupportNewRoute: typeof AccountSupportNewRoute
  AccountReviewsIndexRoute: typeof AccountReviewsIndexRoute
  AccountSupportIndexRoute: typeof AccountSupportIndexRoute
  AccountReviewsEditReviewIdRoute: typeof AccountReviewsEditReviewIdRoute
  AccountReviewsWriteOrderItemIdRoute: typeof AccountReviewsWriteOrderItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-order': {
      id: '/guest-order'
      path: '/guest-order'
      fullPath: '/guest-order'
      preLoaderRoute: typeof GuestOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/inquiries': {
      id: '/account_/inquiries'
      path: '/account/inquiries'
      fullPath: '/account/inquiries'
      preLoaderRoute: typeof AccountInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/wishlist': {
      id: '/account_/wishlist'
      path: '/account/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/complete': {
      id: '/checkout/complete'
      path: '/checkout/complete'
      fullPath: '/checkout/complete'
      preLoaderRoute: typeof CheckoutCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/reviews/': {
      id: '/account_/reviews/'
      path: '/account/reviews'
      fullPath: '/account/reviews/'
      preLoaderRoute: typeof AccountReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/support/': {
      id: '/account_/support/'
      path: '/account/support'
      fullPath: '/account/support/'
      preLoaderRoute: typeof AccountSupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/support/$inquiryId': {
      id: '/account_/support/$inquiryId'
      path: '/account/support/$inquiryId'
      fullPath: '/account/support/$inquiryId'
      preLoaderRoute: typeof AccountSupportInquiryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/support/new': {
      id: '/account_/support/new'
      path: '/account/support/new'
      fullPath: '/account/support/new'
      preLoaderRoute: typeof AccountSupportNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/reviews/edit/$reviewId': {
      id: '/account_/reviews/edit/$reviewId'
      path: '/account/reviews/edit/$reviewId'
      fullPath: '/account/reviews/edit/$reviewId'
      preLoaderRoute: typeof AccountReviewsEditReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/reviews/write/$orderItemId': {
      id: '/account_/reviews/write/$orderItemId'
      path: '/account/reviews/write/$orderItemId'
      fullPath: '/account/reviews/write/$orderItemId'
      preLoaderRoute: typeof AccountReviewsWriteOrderItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CouponsRoute: CouponsRoute,
  GuestOrderRoute: GuestOrderRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  PointsRoute: PointsRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AccountInquiriesRoute: AccountInquiriesRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CheckoutCompleteRoute: CheckoutCompleteRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  AccountSupportInquiryIdRoute: AccountSupportInquiryIdRoute,
  AccountSupportNewRoute: AccountSupportNewRoute,
  AccountReviewsIndexRoute: AccountReviewsIndexRoute,
  AccountSupportIndexRoute: AccountSupportIndexRoute,
  AccountReviewsEditReviewIdRoute: AccountReviewsEditReviewIdRoute,
  AccountReviewsWriteOrderItemIdRoute: AccountReviewsWriteOrderItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
